version: "3"
services:
  springboot-app:
    image: prateekjain348/movie-management
    build: .
    ports:
      - 8080:8080
    environment:
<<<<<<< HEAD
      DB_HOST: mysqldb
      DB_USERNAME: root
      DB_PASSWORD: root
=======
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
>>>>>>> e4589d5e5f9d2036e710cfbe44129a60dc781280
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: prateekjain348/movie-database
    ports:
      - 3306:3306