version: "3"
services:
  springboot-app:
    image: prateekjain348/movie-management
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: mysqldb
      DB_USERNAME: root
      DB_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: prateekjain348/movie-database
    ports:
      - 3306:3306