version: "3"
services:
  springboot-app:
    image: prateekjain348/movie-management
    build: .
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      DB_HOST: mysqldb
      DB_USERNAME: root
      DB_PASSWORD: password
      MYSQL_PORT: 3306
  mysqldb:
    environment:
      MYSQL_USER=: root
      MYSQL_ROOT_PASSWORD: password
    container_name: mysqldb
    image: prateekjain348/movie-database
    ports:
      - 3306:3306