# Deployment specification begins here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    tier: database
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysqldb
        tier: database
    spec:
      containers:
        - name: mysqldb
          image: prateekjain348/movie-database
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysqldb
---
# Define a 'Service' To Expose MySQL to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    tier: database
spec:
#  clusterIP: None
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysqldb
    tier: database
